resolver: lts-3.4
packages:
  - serversession
  - serversession-backend-acid-state
  - serversession-backend-persistent
  - serversession-backend-redis
  - serversession-frontend-snap
  - serversession-frontend-wai
  - serversession-frontend-yesod
  - examples/serversession-example-yesod-persistent
flags:
  serversession:
    lib-Werror: true
  serversession-backend-acid-state:
    lib-Werror: true
  serversession-backend-persistent:
    lib-Werror: true
  serversession-backend-redis:
    lib-Werror: true
  serversession-frontend-snap:
    lib-Werror: true
  serversession-frontend-wai:
    lib-Werror: true
  serversession-frontend-yesod:
    lib-Werror: true
extra-deps:
  - acid-state-0.14.0
  - nonce-1.0.2
  - wai-session-0.3.2
